# Generated by Django 4.0.4 on 2022-05-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Batch_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_id',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
